# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
Linux.create(:q => 'ls')
Linux.create(:q => 'ls -ltr')
Linux.create(:q => 'cat')
Linux.create(:q => 'man')
Linux.create(:q => 'top')
Linux.create(:q => 'netstat')
Linux.create(:q => 'nc')
Linux.create(:q => 'pwd')
Linux.create(:q => 'who')
Linux.create(:q => 'ifconfig')
Git.create(:q => 'git add .')
Git.create(:q => 'git commit -m')
Git.create(:q => 'git push origin main')
Git.create(:q => 'git checkout -b')
Git.create(:q => 'git init')
Git.create(:q => 'git remote add origin')
Git.create(:q => 'git clone')
Git.create(:q => 'git pull')
Git.create(:q => 'git merge')
Git.create(:q => 'git fetch')
Rail.create(:q => 'rails new .')
Rail.create(:q => 'rails g controller')
Rail.create(:q => 'rails g model')
Rail.create(:q => 'rails destroy controller')
Rail.create(:q => 'rails g migration')
Rail.create(:q => 'rails db:migrate:reset')
Rail.create(:q => 'rails s')
Rail.create(:q => 'rails c')
Rail.create(:q => 'rails routes')